### ISSUE TITLE
Can't Download APK file up to 2GB From Store

### ISSUE THREAD

**Issue by gnakale** [wso2-attic/product-emm#246]
Hello,

When I try to download my apk file (2GB). The download start correctly but never completes.
The download correctly completes for the more smaller file .
In my test, the download manager crash for the file bigger than 1.7GB

**Comment by kasundananjaya** [comment]
What's your device OS version? Actually if download manager fails downloading this, it's beyond our control as we use Androids' built in download manager for downloads. But if your device vendor has not released a patch/OS upgrade for this issue, you can try changing WSO2 android agent app to use HTTPClient to download the file rather than using the download manager. It's easily switchable in code (Check line 435 onward on https://github.com/wso2/product-emm/blob/master/modules/mobile-agents/android/client/client/src/main/java/org/wso2/emm/agent/api/ApplicationManager.java). You can use chunking for large files as well.
