### ISSUE TITLE
Device Owner Permissions

### ISSUE THREAD

**Issue by ghost** [wso2-attic/product-emm#379]
Hi,
I am testing the wso2 emm on an android device. I have set up the EMM server and linked an android device to it by just enrolling the device to the server instead of setting up the work profile. In order to apply some policies like Restricting Bluetooth access, the agent application should be a device ower. How do i set my device as a device owner? Is it possibile only programmatically using 'dpm' or is there any way to do it via the application settings on the phone? 

PS: The application is a device administrator. But the policy restrictions like disable volume buttons, Bluetooth disabling doesnt work.

Edit: I tried setting up the work profile too. But the restrictions still dont work. Help Please.

**Comment by kasundananjaya** [comment]
Once your initial device setup is done for the first time, there's no setting etc to change the owner as such.
Please follow : https://docs.wso2.com/display/IoTS300/Device+Ownership+Application

**Comment by Spathire** [comment]
Sorry but I did not get your answer. 

Let me brief the scenario once again.

I have a device and a wso2emm server. Through the admin user, I have logged into the emm server. and enrolled the device the device i have by setting up work profile on the admin/admin login credentials. Now I tried creating a policy which includes restrictions namely disable cross profile copy/paste, disable screenshot, disable of camera. When I apply the changes to the device through emm server, none of the restrictions work. I understood that disabled screenshot only works in the work profile, but it is not functioning. even after policy application, I am able to take screenshots and able to copy paste. 

Can you please tell me why is that?

**Comment by kasundananjaya** [comment]
Hi, In this scenario, User refers to "EMM Agent Administration profile", so other than Camera operation above, others require device/profile owner permission. If you have already setup the device (I mean unboxing and start for the first time, then set your user accounts etc), you already have setup the device owner. If you wanna change it, you have to do it manually via ADB and how to do that is mentioned in the link I shared above.  

Plus, if camera lock etc are not working, that can also be an issue regarding connectivity between the device/server (so just do a simple operation like send notification etc and see if it works).

**Comment by Spathire** [comment]
I got into hand a device with super user permissions so that i can directly push the apps into the system/priv-app folder. As I could directly push the system app into the system apps folder making it a system app, I assumed that I could sign the three apps with any key but the same key for three of them. SO i signed the service application and the agent application with platform keys as described [here](https://stackoverflow.com/a/3651653/8000126). 

I have first installed the signed system service application, and made it a dpm. In order to check i opened to the device_owner.xml (in my case it is device_owner_2.xml) and found it empty but on the device I am unable to disable the device administrator. and then I tried installing the client app which took a lot of time to rebuild, signed it same keys as service application and tried pushing it to the device. and from then my phone doesnt reboot. I am able to access the entire file system through the adb. So I deleted the system service app and client app and device_owner.xml. But the issue still persists. It doesnt boot to the home screen. Please help. This is very critical issue.

**Comment by MayukhaC** [comment]
@Spathire 
Did you get the restrictions working?

**Comment by kasundananjaya** [comment]
@Spathire That's strange. Even in the android official issue log, there's no such issue reported. Can you try dpm command to disable device owner? Else you will have to factory rest the device via settings. Can you get back to us with the results?
